name: Check Markdown Links
on: [push, pull_request]

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Markdown link check
        uses: gaurav-nelson/github-action-markdown-link-check@v1